// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivityLevel
 */
export type ActivityLevel = 'sedentary' | 'lightly_active' | 'moderately_active' | 'very_active' | 'super_active';

/**
 * BodyMetrics
 *
 * Calculated body composition metrics with camelCase serialization.
 */
export type BodyMetrics = {
    /**
     * Weightkg
     */
    weightKg: number;
    /**
     * Heightcm
     */
    heightCm: number;
    /**
     * Bmi
     */
    bmi: number;
    /**
     * Bmistatus
     */
    bmiStatus: string;
    /**
     * Ffmkg
     */
    ffmKg?: number | null;
    /**
     * Fatmasskg
     */
    fatMassKg?: number | null;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChatActionType
 */
export type ChatActionType = 'log_food' | 'log_exercise' | 'reset' | 'none';

/**
 * ChatAttachmentType
 */
export type ChatAttachmentType = 'image' | 'audio' | 'none';

/**
 * ChatMessageCreate
 *
 * Schema for creating a chat message.
 */
export type ChatMessageCreate = {
    /**
     * Content
     */
    content: string;
    attachment_type?: ChatAttachmentType;
    /**
     * Attachment Url
     */
    attachment_url?: string | null;
};

/**
 * ChatMessagePublic
 *
 * Public response model for chat message with camelCase serialization.
 */
export type ChatMessagePublic = {
    /**
     * Id
     */
    id: string;
    role: ChatMessageRole;
    /**
     * Content
     */
    content: string;
    actionType: ChatActionType;
    /**
     * Actiondata
     */
    actionData?: {
        [key: string]: unknown;
    } | null;
    attachmentType: ChatAttachmentType;
    /**
     * Attachmenturl
     */
    attachmentUrl?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * ChatMessageRole
 */
export type ChatMessageRole = 'user' | 'assistant';

/**
 * ChatMessagesPublic
 *
 * List response for chat messages with camelCase serialization.
 */
export type ChatMessagesPublic = {
    /**
     * Data
     */
    data: Array<ChatMessagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DailyLogsResponse
 *
 * Combined response for today's logs with camelCase serialization.
 */
export type DailyLogsResponse = {
    /**
     * Meallogs
     */
    mealLogs: Array<MealLogPublic>;
    /**
     * Exerciselogs
     */
    exerciseLogs: Array<ExerciseLogPublic>;
};

/**
 * DailySummary
 *
 * Daily progress summary with camelCase serialization.
 */
export type DailySummary = {
    /**
     * Caloriesconsumed
     */
    caloriesConsumed: number;
    /**
     * Caloriestarget
     */
    caloriesTarget: number;
    /**
     * Proteinconsumed
     */
    proteinConsumed: number;
    /**
     * Proteintarget
     */
    proteinTarget: number;
    /**
     * Workoutscompleted
     */
    workoutsCompleted: number;
    /**
     * Caloriesremaining
     */
    caloriesRemaining: number;
    /**
     * Proteinremaining
     */
    proteinRemaining: number;
};

/**
 * EnergyAvailability
 *
 * Energy Availability metrics with camelCase serialization.
 */
export type EnergyAvailability = {
    /**
     * Eakcalperkgffm
     */
    eaKcalPerKgFfm?: number | null;
    /**
     * Eastatus
     */
    eaStatus: string;
};

/**
 * EnergyMetrics
 *
 * Calculated energy expenditure metrics with camelCase serialization.
 */
export type EnergyMetrics = {
    /**
     * Bmr
     */
    bmr: number;
    /**
     * Bmrequation
     */
    bmrEquation: string;
    /**
     * Activitymultiplier
     */
    activityMultiplier: number;
    /**
     * Neat
     */
    neat: number;
    /**
     * Basetdee
     */
    baseTdee: number;
    /**
     * Dailydeficit
     */
    dailyDeficit: number;
    /**
     * Estimateddailycalories
     */
    estimatedDailyCalories: number;
};

/**
 * ExerciseLogCreate
 */
export type ExerciseLogCreate = {
    /**
     * Exercise Name
     */
    exercise_name: string;
    /**
     * Sets
     */
    sets: number;
    /**
     * Reps
     */
    reps: number;
    /**
     * Weight Kg
     */
    weight_kg: number;
};

/**
 * ExerciseLogPublic
 *
 * Public response model for exercise log with camelCase serialization.
 */
export type ExerciseLogPublic = {
    /**
     * Exercisename
     */
    exerciseName: string;
    /**
     * Sets
     */
    sets: number;
    /**
     * Reps
     */
    reps: number;
    /**
     * Weightkg
     */
    weightKg: number;
    /**
     * Id
     */
    id: string;
    /**
     * Loggedat
     */
    loggedAt: string;
};

/**
 * GoalMethod
 */
export type GoalMethod = 'maintenance' | 'very_slow_cut' | 'slow_cut' | 'standard_cut' | 'aggressive_cut' | 'very_aggressive_cut' | 'slow_gain' | 'moderate_gain' | 'custom';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MealLogCreate
 */
export type MealLogCreate = {
    /**
     * Meal Name
     */
    meal_name: string;
    /**
     * Meal Type
     */
    meal_type: string;
    /**
     * Calories
     */
    calories: number;
    /**
     * Protein G
     */
    protein_g: number;
    /**
     * Carbs G
     */
    carbs_g: number;
    /**
     * Fat G
     */
    fat_g: number;
};

/**
 * MealLogPublic
 *
 * Public response model for meal log with camelCase serialization.
 */
export type MealLogPublic = {
    /**
     * Mealname
     */
    mealName: string;
    /**
     * Mealtype
     */
    mealType: string;
    /**
     * Calories
     */
    calories: number;
    /**
     * Proteing
     */
    proteinG: number;
    /**
     * Carbsg
     */
    carbsG: number;
    /**
     * Fatg
     */
    fatG: number;
    /**
     * Id
     */
    id: string;
    /**
     * Loggedat
     */
    loggedAt: string;
};

/**
 * MealPlanPublic
 */
export type MealPlanPublic = {
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Meal Type
     */
    meal_type: string;
    /**
     * Item Name
     */
    item_name: string;
    /**
     * Calories
     */
    calories: number;
    /**
     * Protein G
     */
    protein_g: number;
    /**
     * Carbs G
     */
    carbs_g: number;
    /**
     * Fat G
     */
    fat_g: number;
    /**
     * Id
     */
    id: string;
};

/**
 * MealPlansPublic
 */
export type MealPlansPublic = {
    /**
     * Data
     */
    data: Array<MealPlanPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProfileMetrics
 *
 * Combined profile metrics response with camelCase serialization.
 */
export type ProfileMetrics = {
    bodyMetrics: BodyMetrics;
    energyMetrics: EnergyMetrics;
    energyAvailability: EnergyAvailability;
    weeklySummary: WeeklySummary;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TrainingProgramPublic
 */
export type TrainingProgramPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Days Per Week
     */
    days_per_week: number;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Id
     */
    id: string;
};

/**
 * TrainingProgramsPublic
 */
export type TrainingProgramsPublic = {
    /**
     * Data
     */
    data: Array<TrainingProgramPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TrainingRoutinePublic
 */
export type TrainingRoutinePublic = {
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Exercise Name
     */
    exercise_name: string;
    /**
     * Machine Hint
     */
    machine_hint?: string | null;
    /**
     * Sets
     */
    sets: number;
    /**
     * Reps
     */
    reps: number;
    /**
     * Target Load Kg
     */
    target_load_kg: number;
    /**
     * Id
     */
    id: string;
    /**
     * Program Id
     */
    program_id: string;
};

/**
 * TrainingRoutinesPublic
 */
export type TrainingRoutinesPublic = {
    /**
     * Data
     */
    data: Array<TrainingRoutinePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Body Fat Percentage
     */
    body_fat_percentage?: number | null;
    goal_method?: GoalMethod | null;
    /**
     * Goal Weight Kg
     */
    goal_weight_kg?: number | null;
    /**
     * Custom Kg Per Week
     */
    custom_kg_per_week?: number | null;
    /**
     * Custom Kcal Per Day
     */
    custom_kcal_per_day?: number | null;
    activity_level?: ActivityLevel | null;
    /**
     * Selected Program Id
     */
    selected_program_id?: string | null;
    /**
     * Protein G Per Kg
     */
    protein_g_per_kg?: number;
    /**
     * Fat Rest G Per Kg
     */
    fat_rest_g_per_kg?: number;
    /**
     * Fat Train G Per Kg
     */
    fat_train_g_per_kg?: number;
    /**
     * Tef Factor
     */
    tef_factor?: number;
    /**
     * Onboarding Complete
     */
    onboarding_complete?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserProfilePublic
 *
 * Public response model for user profile with camelCase serialization.
 */
export type UserProfilePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Weightkg
     */
    weightKg?: number | null;
    /**
     * Heightcm
     */
    heightCm?: number | null;
    /**
     * Bodyfatpercentage
     */
    bodyFatPercentage?: number | null;
    goalMethod?: GoalMethod | null;
    /**
     * Goalweightkg
     */
    goalWeightKg?: number | null;
    activityLevel?: ActivityLevel | null;
    /**
     * Selectedprogramid
     */
    selectedProgramId?: string | null;
    /**
     * Proteingperkg
     */
    proteinGPerKg: number;
    /**
     * Fatrestgperkg
     */
    fatRestGPerKg: number;
    /**
     * Fattraingperkg
     */
    fatTrainGPerKg: number;
    /**
     * Onboardingcomplete
     */
    onboardingComplete: boolean;
};

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Body Fat Percentage
     */
    body_fat_percentage?: number | null;
    goal_method?: GoalMethod | null;
    /**
     * Goal Weight Kg
     */
    goal_weight_kg?: number | null;
    /**
     * Custom Kg Per Week
     */
    custom_kg_per_week?: number | null;
    /**
     * Custom Kcal Per Day
     */
    custom_kcal_per_day?: number | null;
    activity_level?: ActivityLevel | null;
    /**
     * Protein G Per Kg
     */
    protein_g_per_kg?: number | null;
    /**
     * Fat Rest G Per Kg
     */
    fat_rest_g_per_kg?: number | null;
    /**
     * Fat Train G Per Kg
     */
    fat_train_g_per_kg?: number | null;
    /**
     * Tef Factor
     */
    tef_factor?: number | null;
    /**
     * Onboarding Complete
     */
    onboarding_complete?: boolean | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Body Fat Percentage
     */
    body_fat_percentage?: number | null;
    goal_method?: GoalMethod | null;
    /**
     * Goal Weight Kg
     */
    goal_weight_kg?: number | null;
    /**
     * Custom Kg Per Week
     */
    custom_kg_per_week?: number | null;
    /**
     * Custom Kcal Per Day
     */
    custom_kcal_per_day?: number | null;
    activity_level?: ActivityLevel | null;
    /**
     * Selected Program Id
     */
    selected_program_id?: string | null;
    /**
     * Protein G Per Kg
     */
    protein_g_per_kg?: number;
    /**
     * Fat Rest G Per Kg
     */
    fat_rest_g_per_kg?: number;
    /**
     * Fat Train G Per Kg
     */
    fat_train_g_per_kg?: number;
    /**
     * Tef Factor
     */
    tef_factor?: number;
    /**
     * Onboarding Complete
     */
    onboarding_complete?: boolean;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Weight Kg
     */
    weight_kg?: number | null;
    /**
     * Height Cm
     */
    height_cm?: number | null;
    /**
     * Body Fat Percentage
     */
    body_fat_percentage?: number | null;
    goal_method?: GoalMethod | null;
    /**
     * Goal Weight Kg
     */
    goal_weight_kg?: number | null;
    /**
     * Custom Kg Per Week
     */
    custom_kg_per_week?: number | null;
    /**
     * Custom Kcal Per Day
     */
    custom_kcal_per_day?: number | null;
    activity_level?: ActivityLevel | null;
    /**
     * Selected Program Id
     */
    selected_program_id?: string | null;
    /**
     * Protein G Per Kg
     */
    protein_g_per_kg?: number;
    /**
     * Fat Rest G Per Kg
     */
    fat_rest_g_per_kg?: number;
    /**
     * Fat Train G Per Kg
     */
    fat_train_g_per_kg?: number;
    /**
     * Tef Factor
     */
    tef_factor?: number;
    /**
     * Onboarding Complete
     */
    onboarding_complete?: boolean;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WeeklySummary
 *
 * Weekly projection metrics with camelCase serialization.
 */
export type WeeklySummary = {
    /**
     * Weeklydeficitkcal
     */
    weeklyDeficitKcal: number;
    /**
     * Expectedlosskgperweek
     */
    expectedLossKgPerWeek: number;
    /**
     * Monthlylosskg
     */
    monthlyLossKg: number;
    /**
     * Totaltogoalkg
     */
    totalToGoalKg?: number | null;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ProfileGetCurrentUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me';
};

export type ProfileGetCurrentUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfilePublic;
};

export type ProfileGetCurrentUserProfileResponse = ProfileGetCurrentUserProfileResponses[keyof ProfileGetCurrentUserProfileResponses];

export type ProfileUpdateCurrentUserProfileData = {
    body: UserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me';
};

export type ProfileUpdateCurrentUserProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProfileUpdateCurrentUserProfileError = ProfileUpdateCurrentUserProfileErrors[keyof ProfileUpdateCurrentUserProfileErrors];

export type ProfileUpdateCurrentUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserProfilePublic;
};

export type ProfileUpdateCurrentUserProfileResponse = ProfileUpdateCurrentUserProfileResponses[keyof ProfileUpdateCurrentUserProfileResponses];

export type ProfileGetCurrentUserMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me/metrics';
};

export type ProfileGetCurrentUserMetricsResponses = {
    /**
     * Successful Response
     */
    200: ProfileMetrics;
};

export type ProfileGetCurrentUserMetricsResponse = ProfileGetCurrentUserMetricsResponses[keyof ProfileGetCurrentUserMetricsResponses];

export type ProgramsListTrainingProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/programs';
};

export type ProgramsListTrainingProgramsResponses = {
    /**
     * Successful Response
     */
    200: TrainingProgramsPublic;
};

export type ProgramsListTrainingProgramsResponse = ProgramsListTrainingProgramsResponses[keyof ProgramsListTrainingProgramsResponses];

export type ProgramsSelectProgramData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/programs/{program_id}/select';
};

export type ProgramsSelectProgramErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProgramsSelectProgramError = ProgramsSelectProgramErrors[keyof ProgramsSelectProgramErrors];

export type ProgramsSelectProgramResponses = {
    /**
     * Successful Response
     */
    200: UserProfilePublic;
};

export type ProgramsSelectProgramResponse = ProgramsSelectProgramResponses[keyof ProgramsSelectProgramResponses];

export type ProgramsGetProgramRoutinesData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: {
        /**
         * Day Of Week
         */
        day_of_week?: number | null;
    };
    url: '/api/v1/programs/{program_id}/routines';
};

export type ProgramsGetProgramRoutinesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProgramsGetProgramRoutinesError = ProgramsGetProgramRoutinesErrors[keyof ProgramsGetProgramRoutinesErrors];

export type ProgramsGetProgramRoutinesResponses = {
    /**
     * Successful Response
     */
    200: TrainingRoutinesPublic;
};

export type ProgramsGetProgramRoutinesResponse = ProgramsGetProgramRoutinesResponses[keyof ProgramsGetProgramRoutinesResponses];

export type PlansGetTodaysTrainingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/training/today';
};

export type PlansGetTodaysTrainingResponses = {
    /**
     * Successful Response
     */
    200: TrainingRoutinesPublic;
};

export type PlansGetTodaysTrainingResponse = PlansGetTodaysTrainingResponses[keyof PlansGetTodaysTrainingResponses];

export type PlansGetTodaysMealPlanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/meal/today';
};

export type PlansGetTodaysMealPlanResponses = {
    /**
     * Successful Response
     */
    200: MealPlansPublic;
};

export type PlansGetTodaysMealPlanResponse = PlansGetTodaysMealPlanResponses[keyof PlansGetTodaysMealPlanResponses];

export type LogsGetTodaysLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logs/today';
};

export type LogsGetTodaysLogsResponses = {
    /**
     * Successful Response
     */
    200: DailyLogsResponse;
};

export type LogsGetTodaysLogsResponse = LogsGetTodaysLogsResponses[keyof LogsGetTodaysLogsResponses];

export type LogsLogMealData = {
    body: MealLogCreate;
    path?: never;
    query?: never;
    url: '/api/v1/logs/meal';
};

export type LogsLogMealErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsLogMealError = LogsLogMealErrors[keyof LogsLogMealErrors];

export type LogsLogMealResponses = {
    /**
     * Successful Response
     */
    200: MealLogPublic;
};

export type LogsLogMealResponse = LogsLogMealResponses[keyof LogsLogMealResponses];

export type LogsLogExerciseData = {
    body: ExerciseLogCreate;
    path?: never;
    query?: never;
    url: '/api/v1/logs/exercise';
};

export type LogsLogExerciseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsLogExerciseError = LogsLogExerciseErrors[keyof LogsLogExerciseErrors];

export type LogsLogExerciseResponses = {
    /**
     * Successful Response
     */
    200: ExerciseLogPublic;
};

export type LogsLogExerciseResponse = LogsLogExerciseResponses[keyof LogsLogExerciseResponses];

export type SummaryGetTodaysSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/summary/today';
};

export type SummaryGetTodaysSummaryResponses = {
    /**
     * Successful Response
     */
    200: DailySummary;
};

export type SummaryGetTodaysSummaryResponse = SummaryGetTodaysSummaryResponses[keyof SummaryGetTodaysSummaryResponses];

export type ChatClearMessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/messages';
};

export type ChatClearMessagesResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ChatClearMessagesResponse = ChatClearMessagesResponses[keyof ChatClearMessagesResponses];

export type ChatGetMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/chat/messages';
};

export type ChatGetMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatGetMessagesError = ChatGetMessagesErrors[keyof ChatGetMessagesErrors];

export type ChatGetMessagesResponses = {
    /**
     * Successful Response
     */
    200: ChatMessagesPublic;
};

export type ChatGetMessagesResponse = ChatGetMessagesResponses[keyof ChatGetMessagesResponses];

export type ChatSendMessageData = {
    body: ChatMessageCreate;
    path?: never;
    query?: never;
    url: '/api/v1/chat/messages';
};

export type ChatSendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatSendMessageError = ChatSendMessageErrors[keyof ChatSendMessageErrors];

export type ChatSendMessageResponses = {
    /**
     * Successful Response
     */
    200: ChatMessagePublic;
};

export type ChatSendMessageResponse = ChatSendMessageResponses[keyof ChatSendMessageResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type DemoGetDemoUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo/users';
};

export type DemoGetDemoUsersResponses = {
    /**
     * Response Demo-Get Demo Users
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type DemoGetDemoUsersResponse = DemoGetDemoUsersResponses[keyof DemoGetDemoUsersResponses];

export type DemoDemoLoginData = {
    body?: never;
    path: {
        /**
         * Persona
         */
        persona: string;
    };
    query?: never;
    url: '/api/v1/demo/login/{persona}';
};

export type DemoDemoLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoDemoLoginError = DemoDemoLoginErrors[keyof DemoDemoLoginErrors];

export type DemoDemoLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type DemoDemoLoginResponse = DemoDemoLoginResponses[keyof DemoDemoLoginResponses];
