"""Add chat_message table

Revision ID: 45b4c5a848fe
Revises: f001_foundation
Create Date: 2025-12-05 14:37:06.675817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '45b4c5a848fe'
down_revision = 'f001_foundation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatmessagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('action_type', sa.Enum('LOG_FOOD', 'LOG_EXERCISE', 'RESET', 'NONE', name='chatactiontype'), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('attachment_type', sa.Enum('IMAGE', 'AUDIO', 'NONE', name='chatattachmenttype'), nullable=False),
    sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_user_id'), 'chat_message', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_user_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
